[platformio]
default_envs = okua_node_esp32dev
src_dir = firmware/okua_node_udp_v1
include_dir = firmware/okua_node_udp_v1

[env:okua_node_esp32dev]
platform = espressif32 @ 6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
